spring.application.name=backend

#habilit the console web
spring.h2.console.enabled=true

# URL configuration for the conection to data
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=123